# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c79d2363f59b6ce8d5a2691ab5461f825126d378b3dc58d06e9dfaaf4549ce67d06b9a73f651aed66331dfc0efa0e40c38fcf6bc93bec370a65c966510e2e424

test:
  secret_key_base: 3ec7192dc0d6d54aaa257537aa3bf75104e3d815f727835d6c5eb5b5d9f13b14408b11cc046e07785cfc278646baf200fa89b09c40d547aacfa32cf01375f474

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
